### PR TITLE
minimal logging

### PR DESCRIPTION
**Pull request by ishaq**
I noticed Ian removed his Logging.h, not sure of the rationale, shouldn't we still use some sort of minimal logging system instead of `errs() << ...`.

I had introduced these changes to my fork while trying to understand Occam, it uses LLVM's `DEBUG` macro to only log when `-debug` switch is on.

Please feel free to discard if I am being _the new guy who doesn't understand crap and is only trying to get attention :-)_

### CODE REVIEW

**Comment by ianamason** [comment]
I removed the logging because it was redundant.

```
  export OCCAM_LOGFILE={absolute path to log location}
  export OCCAM_LOGLEVEL={INFO, WARNING, or ERROR}
```

does the job (have not tested the level stuff, but the errs() stuff gets redirected to the logfile.

**Comment by ishaq** [comment]
`errs()` stuff is still compiled into the pass by LLVM, the advantage of using DEBUG macro is that it strips the code for release builds.

just my two cents.

**Comment by ianamason** [comment]
Yes  I am sure we can optimize.  Might do so once the thing is in a more polished state.

**Comment by ashish-gehani** [comment]
The commits related to debugging, logging, and counting instructions (why?) should be in separate pull requests. Since the Python frontend has been rewritten, the changes may no longer be usable.

**Pull request closed without merging**
